export var Constants = {
  RE_IMAGINE: 'RE_IMAGINE',
  FILL_UP_YOUR_SPACE: 'FILL_UP_YOUR_SPACE',
  CREATE_FROM_IMAGINATION: 'CREATE_FROM_IMAGINATION',

  UPLOAD_FLOW: "UPLOAD_FLOW",
  RESULTS_FLOW: "RESULTS_FLOW",
  CUSTOMIZATION_FLOW: "CUSTOMIZATION_FLOW",

  CURRENT_PLAN: "CURRENT_PLAN",
  UPGRADE_PLAN: "UPGRADE_PLAN",
  DOWNGRADE_PLAN: "DOWNGRADE_PLAN",
};

export const UI_FRAMEWORK = Object.freeze({
  VUE_UI: 'vue_ui',
});
